//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public Calendar()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int CalendarId { get; set; }
        public string CalendarAlias { get; set; }
        public int OrganizationId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual Office Office { get; set; }
    }
}
