//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Attendees = new HashSet<Person>();
        }
    
        public int NonRecurringEventId { get; set; }
        public string Description { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int HostPersonId { get; set; }
        public int SponsorPersonId { get; set; }
        public string Recurrance { get; set; }
        public string Title { get; set; }
        public int LocationId { get; set; }
        public int AddressId { get; set; }
    
        public virtual Person Host { get; set; }
        public virtual Person Sponsor { get; set; }
        public virtual Calendar Calendar { get; set; }
        public virtual ICollection<Person> Attendees { get; set; }
        public virtual Address Address { get; set; }
    }
}
