//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Offices = new HashSet<Office>();
        }
    
        public int MemberId { get; set; }
        public int OrganizationId { get; set; }
        public int PersonId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Office> Offices { get; set; }
    }
}
