//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int OfficeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int MemberId { get; set; }
        public int OrganizationId { get; set; }
        public string Email { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Calendar Calendar { get; set; }
    }
}
