//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGOKnights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Memberships = new HashSet<Member>();
            this.Calendars = new HashSet<Calendar>();
            this.Offices = new HashSet<Office>();
        }
    
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Member> Memberships { get; set; }
        public virtual ICollection<Calendar> Calendars { get; set; }
        public virtual ICollection<Office> Offices { get; set; }
    }
}
